
server:
  port: 8080

spring:
  datasource:
    #    ??????????????
    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pixelstrike #?servierTimezone=UTC
    username: root
#    password: 1234
    password: abcABC369258
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 50MB
#      max-request-size: 100MB
  webflux:
    multipart:
      max-in-memory-size: 50MB # 调整为你需要的大小
      max-parts: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1


# ===============================================
#  游戏核心参数配置
# ===============================================
game:
  matchmaking:
    room-max-size: 2 # 匹配房间大小
  rules:
    kills-to-win: 2 # 胜利所需的击杀数
    max-duration-ms: 300000 # 游戏最长持续时间 (5分钟)
    countdown-seconds: 5 # 开局倒计时
  player:
    max-health: 100 # 玩家最大生命值
    initial-ammo: 30 # 初始弹药
    respawn-time-ms: 3000 # 复活时间 (3秒)
    height: 40.0 # 玩家高度，用于命中判定
  physics:
    gravity: 0.8 # 重力加速度
    ground-y: 500.0 # 地面Y坐标
    death-zone-y: 1200.0 # 掉落死亡区域的Y坐标
  weapon:
    damage: 25 # 武器伤害
  engine:
    tick-rate-ms: 16 # 游戏服务器的Tick频率 (ms), 16ms ≈ 62.5Hz