
server:
  port: 8080

spring:
  datasource:
    #    ??????????????
    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pixelstrike #?servierTimezone=UTC
    username: root
    password: 1234
    # password: abcABC369258
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 50MB
#      max-request-size: 100MB
  webflux:
    multipart:
      max-in-memory-size: 50MB # 调整为你需要的大小
      max-parts: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1